package cf.crm;

// Generated 2014-7-12 15:41:18 by Hibernate Tools 3.6.0

/**
 * Orderrecordproduct generated by hbm2java
 */
public class Orderrecordproduct implements java.io.Serializable {

	private OrderrecordproductId id;
	private Orderrecord orderrecord;
	private Product product;
	private String orreprId;
	private int orreprNum;

	public Orderrecordproduct() {
	}

	public Orderrecordproduct(OrderrecordproductId id, Orderrecord orderrecord,
			Product product, int orreprNum) {
		this.id = id;
		this.orderrecord = orderrecord;
		this.product = product;
		this.orreprNum = orreprNum;
	}

	public Orderrecordproduct(OrderrecordproductId id, Orderrecord orderrecord,
			Product product, String orreprId, int orreprNum) {
		this.id = id;
		this.orderrecord = orderrecord;
		this.product = product;
		this.orreprId = orreprId;
		this.orreprNum = orreprNum;
	}

	public OrderrecordproductId getId() {
		return this.id;
	}

	public void setId(OrderrecordproductId id) {
		this.id = id;
	}

	public Orderrecord getOrderrecord() {
		return this.orderrecord;
	}

	public void setOrderrecord(Orderrecord orderrecord) {
		this.orderrecord = orderrecord;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public String getOrreprId() {
		return this.orreprId;
	}

	public void setOrreprId(String orreprId) {
		this.orreprId = orreprId;
	}

	public int getOrreprNum() {
		return this.orreprNum;
	}

	public void setOrreprNum(int orreprNum) {
		this.orreprNum = orreprNum;
	}

}
