package cf.crm;

// Generated 2014-7-12 15:41:18 by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * ServicecustomerId generated by hbm2java
 */
public class ServicecustomerId implements java.io.Serializable {

	private String secuId;
	private String cuId;
	private String seId;
	private String usAllocationId;
	private Date secuAllocationTime;
	private String usDealId;
	private String secuDeal;
	private Date secuDealTime;
	private String secuDealResult;
	private Integer secuSatisfy;

	public ServicecustomerId() {
	}

	public ServicecustomerId(String secuId, String cuId, String seId) {
		this.secuId = secuId;
		this.cuId = cuId;
		this.seId = seId;
	}

	public ServicecustomerId(String secuId, String cuId, String seId,
			String usAllocationId, Date secuAllocationTime, String usDealId,
			String secuDeal, Date secuDealTime, String secuDealResult,
			Integer secuSatisfy) {
		this.secuId = secuId;
		this.cuId = cuId;
		this.seId = seId;
		this.usAllocationId = usAllocationId;
		this.secuAllocationTime = secuAllocationTime;
		this.usDealId = usDealId;
		this.secuDeal = secuDeal;
		this.secuDealTime = secuDealTime;
		this.secuDealResult = secuDealResult;
		this.secuSatisfy = secuSatisfy;
	}

	public String getSecuId() {
		return this.secuId;
	}

	public void setSecuId(String secuId) {
		this.secuId = secuId;
	}

	public String getCuId() {
		return this.cuId;
	}

	public void setCuId(String cuId) {
		this.cuId = cuId;
	}

	public String getSeId() {
		return this.seId;
	}

	public void setSeId(String seId) {
		this.seId = seId;
	}

	public String getUsAllocationId() {
		return this.usAllocationId;
	}

	public void setUsAllocationId(String usAllocationId) {
		this.usAllocationId = usAllocationId;
	}

	public Date getSecuAllocationTime() {
		return this.secuAllocationTime;
	}

	public void setSecuAllocationTime(Date secuAllocationTime) {
		this.secuAllocationTime = secuAllocationTime;
	}

	public String getUsDealId() {
		return this.usDealId;
	}

	public void setUsDealId(String usDealId) {
		this.usDealId = usDealId;
	}

	public String getSecuDeal() {
		return this.secuDeal;
	}

	public void setSecuDeal(String secuDeal) {
		this.secuDeal = secuDeal;
	}

	public Date getSecuDealTime() {
		return this.secuDealTime;
	}

	public void setSecuDealTime(Date secuDealTime) {
		this.secuDealTime = secuDealTime;
	}

	public String getSecuDealResult() {
		return this.secuDealResult;
	}

	public void setSecuDealResult(String secuDealResult) {
		this.secuDealResult = secuDealResult;
	}

	public Integer getSecuSatisfy() {
		return this.secuSatisfy;
	}

	public void setSecuSatisfy(Integer secuSatisfy) {
		this.secuSatisfy = secuSatisfy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServicecustomerId))
			return false;
		ServicecustomerId castOther = (ServicecustomerId) other;

		return ((this.getSecuId() == castOther.getSecuId()) || (this
				.getSecuId() != null && castOther.getSecuId() != null && this
				.getSecuId().equals(castOther.getSecuId())))
				&& ((this.getCuId() == castOther.getCuId()) || (this.getCuId() != null
						&& castOther.getCuId() != null && this.getCuId()
						.equals(castOther.getCuId())))
				&& ((this.getSeId() == castOther.getSeId()) || (this.getSeId() != null
						&& castOther.getSeId() != null && this.getSeId()
						.equals(castOther.getSeId())))
				&& ((this.getUsAllocationId() == castOther.getUsAllocationId()) || (this
						.getUsAllocationId() != null
						&& castOther.getUsAllocationId() != null && this
						.getUsAllocationId().equals(
								castOther.getUsAllocationId())))
				&& ((this.getSecuAllocationTime() == castOther
						.getSecuAllocationTime()) || (this
						.getSecuAllocationTime() != null
						&& castOther.getSecuAllocationTime() != null && this
						.getSecuAllocationTime().equals(
								castOther.getSecuAllocationTime())))
				&& ((this.getUsDealId() == castOther.getUsDealId()) || (this
						.getUsDealId() != null
						&& castOther.getUsDealId() != null && this
						.getUsDealId().equals(castOther.getUsDealId())))
				&& ((this.getSecuDeal() == castOther.getSecuDeal()) || (this
						.getSecuDeal() != null
						&& castOther.getSecuDeal() != null && this
						.getSecuDeal().equals(castOther.getSecuDeal())))
				&& ((this.getSecuDealTime() == castOther.getSecuDealTime()) || (this
						.getSecuDealTime() != null
						&& castOther.getSecuDealTime() != null && this
						.getSecuDealTime().equals(castOther.getSecuDealTime())))
				&& ((this.getSecuDealResult() == castOther.getSecuDealResult()) || (this
						.getSecuDealResult() != null
						&& castOther.getSecuDealResult() != null && this
						.getSecuDealResult().equals(
								castOther.getSecuDealResult())))
				&& ((this.getSecuSatisfy() == castOther.getSecuSatisfy()) || (this
						.getSecuSatisfy() != null
						&& castOther.getSecuSatisfy() != null && this
						.getSecuSatisfy().equals(castOther.getSecuSatisfy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSecuId() == null ? 0 : this.getSecuId().hashCode());
		result = 37 * result
				+ (getCuId() == null ? 0 : this.getCuId().hashCode());
		result = 37 * result
				+ (getSeId() == null ? 0 : this.getSeId().hashCode());
		result = 37
				* result
				+ (getUsAllocationId() == null ? 0 : this.getUsAllocationId()
						.hashCode());
		result = 37
				* result
				+ (getSecuAllocationTime() == null ? 0 : this
						.getSecuAllocationTime().hashCode());
		result = 37 * result
				+ (getUsDealId() == null ? 0 : this.getUsDealId().hashCode());
		result = 37 * result
				+ (getSecuDeal() == null ? 0 : this.getSecuDeal().hashCode());
		result = 37
				* result
				+ (getSecuDealTime() == null ? 0 : this.getSecuDealTime()
						.hashCode());
		result = 37
				* result
				+ (getSecuDealResult() == null ? 0 : this.getSecuDealResult()
						.hashCode());
		result = 37
				* result
				+ (getSecuSatisfy() == null ? 0 : this.getSecuSatisfy()
						.hashCode());
		return result;
	}

}
