package cf.crm;

// Generated 2014-7-12 15:41:18 by Hibernate Tools 3.6.0

/**
 * Servicecustomer generated by hbm2java
 */
public class Servicecustomer implements java.io.Serializable {

	private ServicecustomerId id;
	private Customer customer;
	private Service service;
	private User userByUsAllocationId;
	private User userByUsDealId;

	public Servicecustomer() {
	}

	public Servicecustomer(ServicecustomerId id, Customer customer,
			Service service) {
		this.id = id;
		this.customer = customer;
		this.service = service;
	}

	public Servicecustomer(ServicecustomerId id, Customer customer,
			Service service, User userByUsAllocationId, User userByUsDealId) {
		this.id = id;
		this.customer = customer;
		this.service = service;
		this.userByUsAllocationId = userByUsAllocationId;
		this.userByUsDealId = userByUsDealId;
	}

	public ServicecustomerId getId() {
		return this.id;
	}

	public void setId(ServicecustomerId id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	public User getUserByUsAllocationId() {
		return this.userByUsAllocationId;
	}

	public void setUserByUsAllocationId(User userByUsAllocationId) {
		this.userByUsAllocationId = userByUsAllocationId;
	}

	public User getUserByUsDealId() {
		return this.userByUsDealId;
	}

	public void setUserByUsDealId(User userByUsDealId) {
		this.userByUsDealId = userByUsDealId;
	}

}
