package cf.crm.entity;

// Generated 2014-7-12 22:54:45 by Hibernate Tools 3.6.0

/**
 * Contactperson generated by hbm2java
 */
public class Contactperson implements java.io.Serializable {

	private String copeId;
	private Customer customer;
	private String copeName;
	private String copeSex;
	private String copePosition;
	private String copeTel;
	private String copePhone;
	private String copeNote;

	public Contactperson() {
	}

	public Contactperson(String copeId, Customer customer, String copeName,
			String copeSex, String copePosition, String copeTel) {
		this.copeId = copeId;
		this.customer = customer;
		this.copeName = copeName;
		this.copeSex = copeSex;
		this.copePosition = copePosition;
		this.copeTel = copeTel;
	}

	public Contactperson(String copeId, Customer customer, String copeName,
			String copeSex, String copePosition, String copeTel,
			String copePhone, String copeNote) {
		this.copeId = copeId;
		this.customer = customer;
		this.copeName = copeName;
		this.copeSex = copeSex;
		this.copePosition = copePosition;
		this.copeTel = copeTel;
		this.copePhone = copePhone;
		this.copeNote = copeNote;
	}

	public String getCopeId() {
		return this.copeId;
	}

	public void setCopeId(String copeId) {
		this.copeId = copeId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getCopeName() {
		return this.copeName;
	}

	public void setCopeName(String copeName) {
		this.copeName = copeName;
	}

	public String getCopeSex() {
		return this.copeSex;
	}

	public void setCopeSex(String copeSex) {
		this.copeSex = copeSex;
	}

	public String getCopePosition() {
		return this.copePosition;
	}

	public void setCopePosition(String copePosition) {
		this.copePosition = copePosition;
	}

	public String getCopeTel() {
		return this.copeTel;
	}

	public void setCopeTel(String copeTel) {
		this.copeTel = copeTel;
	}

	public String getCopePhone() {
		return this.copePhone;
	}

	public void setCopePhone(String copePhone) {
		this.copePhone = copePhone;
	}

	public String getCopeNote() {
		return this.copeNote;
	}

	public void setCopeNote(String copeNote) {
		this.copeNote = copeNote;
	}

}
