package cf.crm.entity;

// Generated 2014-7-12 22:54:45 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Salechance generated by hbm2java
 */
public class Salechance implements java.io.Serializable {

	private String sachId;
	private User userByUsCreateId;
	private User userByUsDesignationId;
	private String usOrigin;
	private float usProbability;
	private String usMain;
	private String usCustomerName;
	private String usContanct;
	private String usContanctTel;
	private String usChanceDescribe;
	private Date usCreateTime;
	private Date usDesignationTime;
	private Set developments = new HashSet(0);

	public Salechance() {
	}

	public Salechance(String sachId, User userByUsCreateId,
			float usProbability, String usMain, String usCustomerName,
			String usChanceDescribe, Date usCreateTime) {
		this.sachId = sachId;
		this.userByUsCreateId = userByUsCreateId;
		this.usProbability = usProbability;
		this.usMain = usMain;
		this.usCustomerName = usCustomerName;
		this.usChanceDescribe = usChanceDescribe;
		this.usCreateTime = usCreateTime;
	}

	public Salechance(String sachId, User userByUsCreateId,
			User userByUsDesignationId, String usOrigin, float usProbability,
			String usMain, String usCustomerName, String usContanct,
			String usContanctTel, String usChanceDescribe, Date usCreateTime,
			Date usDesignationTime, Set developments) {
		this.sachId = sachId;
		this.userByUsCreateId = userByUsCreateId;
		this.userByUsDesignationId = userByUsDesignationId;
		this.usOrigin = usOrigin;
		this.usProbability = usProbability;
		this.usMain = usMain;
		this.usCustomerName = usCustomerName;
		this.usContanct = usContanct;
		this.usContanctTel = usContanctTel;
		this.usChanceDescribe = usChanceDescribe;
		this.usCreateTime = usCreateTime;
		this.usDesignationTime = usDesignationTime;
		this.developments = developments;
	}

	public String getSachId() {
		return this.sachId;
	}

	public void setSachId(String sachId) {
		this.sachId = sachId;
	}

	public User getUserByUsCreateId() {
		return this.userByUsCreateId;
	}

	public void setUserByUsCreateId(User userByUsCreateId) {
		this.userByUsCreateId = userByUsCreateId;
	}

	public User getUserByUsDesignationId() {
		return this.userByUsDesignationId;
	}

	public void setUserByUsDesignationId(User userByUsDesignationId) {
		this.userByUsDesignationId = userByUsDesignationId;
	}

	public String getUsOrigin() {
		return this.usOrigin;
	}

	public void setUsOrigin(String usOrigin) {
		this.usOrigin = usOrigin;
	}

	public float getUsProbability() {
		return this.usProbability;
	}

	public void setUsProbability(float usProbability) {
		this.usProbability = usProbability;
	}

	public String getUsMain() {
		return this.usMain;
	}

	public void setUsMain(String usMain) {
		this.usMain = usMain;
	}

	public String getUsCustomerName() {
		return this.usCustomerName;
	}

	public void setUsCustomerName(String usCustomerName) {
		this.usCustomerName = usCustomerName;
	}

	public String getUsContanct() {
		return this.usContanct;
	}

	public void setUsContanct(String usContanct) {
		this.usContanct = usContanct;
	}

	public String getUsContanctTel() {
		return this.usContanctTel;
	}

	public void setUsContanctTel(String usContanctTel) {
		this.usContanctTel = usContanctTel;
	}

	public String getUsChanceDescribe() {
		return this.usChanceDescribe;
	}

	public void setUsChanceDescribe(String usChanceDescribe) {
		this.usChanceDescribe = usChanceDescribe;
	}

	public Date getUsCreateTime() {
		return this.usCreateTime;
	}

	public void setUsCreateTime(Date usCreateTime) {
		this.usCreateTime = usCreateTime;
	}

	public Date getUsDesignationTime() {
		return this.usDesignationTime;
	}

	public void setUsDesignationTime(Date usDesignationTime) {
		this.usDesignationTime = usDesignationTime;
	}

	public Set getDevelopments() {
		return this.developments;
	}

	public void setDevelopments(Set developments) {
		this.developments = developments;
	}

}
