package cf.crm.entity;

// Generated 2014-7-12 16:42:52 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Storage generated by hbm2java
 */
public class Storage implements java.io.Serializable {

	private String stId;
	private String stName;
	private Set products = new HashSet(0);

	public Storage() {
	}

	public Storage(String stId, String stName) {
		this.stId = stId;
		this.stName = stName;
	}

	public Storage(String stId, String stName, Set products) {
		this.stId = stId;
		this.stName = stName;
		this.products = products;
	}

	public String getStId() {
		return this.stId;
	}

	public void setStId(String stId) {
		this.stId = stId;
	}

	public String getStName() {
		return this.stName;
	}

	public void setStName(String stName) {
		this.stName = stName;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
